# Generated by Django 3.1.3 on 2020-12-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='storehash',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='auth',
            name='token',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
