# Generated by Django 3.1.3 on 2020-12-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callback', '0002_auto_20201202_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='storehash',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='auth',
            name='token',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
