# Generated by Django 3.1.3 on 2020-12-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callback', '0003_auto_20201202_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
